services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: backend-app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
